import type {
  AuthLocalization,
  SettingsLocalization,
} from '@better-auth-ui/core'

export const AuthLang_PT_BR = {
  auth: {
    account: 'Conta',
    alreadyHaveAnAccount: 'Já tem uma conta?',
    alreadyVerifiedYourEmail: 'Já verificou seu e-mail?',
    confirmPassword: 'Confirmar senha',
    confirmPasswordPlaceholder: 'Confirmar senha',
    checkYourEmail: 'Verifique seu e-mail para o link de verificação',
    continueWith: 'Continuar com {{provider}}',
    email: 'E-mail',
    emailPlaceholder: 'nome@exemplo.com',
    fieldRequired: 'Este campo é obrigatório',
    forgotPassword: 'Esqueceu a senha?',
    forgotPasswordLink: 'Esqueceu sua senha?',
    hidePassword: 'Ocultar senha',
    invalidEmail: 'Digite um endereço de e-mail válido',
    invalidResetPasswordToken: 'Token de redefinição de senha inválido',
    name: 'Nome',
    namePlaceholder: 'Nome',
    needToCreateAnAccount: 'Não tem uma conta?',
    newPassword: 'Nova senha',
    newPasswordPlaceholder: 'Nova senha',
    openEmailProvider: 'Abrir {{provider}}',
    or: 'OU',
    password: 'Senha',
    passwordPlaceholder: 'Senha',
    passwordResetEmailSent: 'E-mail de redefinição de senha enviado',
    passwordResetSuccess: 'Senha redefinida com sucesso',
    passwordsDoNotMatch: 'As senhas não coincidem',
    rememberMe: 'Lembrar de mim',
    tooLong: 'Use no máximo {{max}} caracteres',
    tooShort: 'Use no mínimo {{min}} caracteres',
    rememberYourPassword: 'Lembrou sua senha?',
    resend: 'Reenviar',
    resendIn: 'Reenviar em {{seconds}}s',
    resetPassword: 'Redefinir senha',
    sendResetLink: 'Enviar link de redefinição',
    showPassword: 'Mostrar senha',
    signIn: 'Entrar',
    signOut: 'Sair',
    signUp: 'Criar conta',
    verificationEmailSent: 'E-mail de verificação enviado!',
    verifyEmail: 'Verificar e-mail',
  } satisfies AuthLocalization,
  settings: {
    account: 'Conta',
    accountUnlinked: 'Conta desvinculada',
    active: 'Ativa',
    activeSessions: 'Sessões ativas',
    avatar: 'Avatar',
    currentSession: 'Sessão atual',
    avatarChangedSuccess: 'Avatar atualizado com sucesso',
    avatarDeletedSuccess: 'Avatar excluído com sucesso',
    changeAvatar: 'Alterar avatar',
    deleteAvatar: 'Excluir avatar',
    link: 'Link',
    linkedAccounts: 'Contas vinculadas',
    linkProvider: 'Vincular sua conta {{provider}}',
    cancel: 'Cancelar',
    copyToClipboard: 'Copiar para a área de transferência',
    changeEmail: 'Alterar e-mail',
    changeEmailSuccess: 'Verifique seu e-mail para confirmar a alteração',
    changePassword: 'Alterar senha',
    changePasswordSuccess: 'Sua senha foi alterada',
    currentPassword: 'Senha atual',
    currentPasswordPlaceholder: 'Senha atual',
    dangerZone: 'Zona de perigo',
    delete: 'Excluir',
    optional: 'Opcional',
    profileUpdatedSuccess: 'Perfil atualizado com sucesso',
    revoke: 'Revogar',
    revokeSession: 'Revogar sessão',
    revokeSessionSuccess: 'Sessão revogada com sucesso',
    saveChanges: 'Salvar alterações',
    setPassword: 'Definir senha',
    setPasswordDescription:
      'Você ainda não tem uma senha. Solicite um link de redefinição para configurá-la.',
    security: 'Segurança',
    settings: 'Configurações',
    time: 'Hora',
    unlinkProvider: 'Desvincular {{provider}}',
    updateEmail: 'Atualizar e-mail',
    updatePassword: 'Atualizar senha',
    uploadAvatar: 'Enviar avatar',
    userProfile: 'Perfil do usuário',
  } satisfies SettingsLocalization,
}
